# Development Environment Configuration
environment: development

cluster:
  name: tmc-cloud-dev
  namespace: tmc-cloud-dev

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

replicas:
  min: 1
  max: 3

storage:
  size: "10Gi"
  class: "local-storage"

monitoring:
  enabled: true
  retention: "7d"

backup:
  enabled: false
  schedule: "0 2 * * *"

security:
  tls: false
  rbac: true